# fly.toml app configuration file generated for vercelspeedtest-next-js on 2025-06-14T22:45:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vercelspeedtest-next-js'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '128mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 128
