# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - speedjstest

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'fly.toml'
      - '.vercalignore'
      - '.dockerignore'
      -  'host.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build
        run: |
          npm i --package-lock-only
          npm install
          npm run build
          mkdir ./standalone
          cp -r .next/standalone/* ./standalone/
          cp -r /.next/static/* ./standalone/.next/static
          
      - name: Zip artifact for deployment
        working-directory: ./standalone
        run: | 
            zip release.zip ./* -r
            zip -r release.zip ".next"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          allowUpdates: "true"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A940D0FFA20C4F928C0739E11E89D550 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AE18E4B494BC42CC82390722D3CD8FA0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B377EEA9715B4D9E90C5BC4886745BF2 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'speedjstest'
          slot-name: 'Production'
          package: .
          
