name: Docker Image build


on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '/.github/workflows/npm-publish.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '/.github/workflows/npm-publish.yml'

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: login to hub  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: blurred123131/speedjs:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: '160.22.78.169'
          username: 'root'
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            docker pull blurred123131/speedjs:latest
            docker compose up -d

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: '176.126.84.41'
          username: 'root'
          password: ${{ secrets.DEPLOY_PASSWORD2 }}
          script: |
            docker pull blurred123131/speedjs:latest
            cd plex && docker compose up -d
