name: Docker Image build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package.json'
      - run: npm ci
      - run: npm test
  
      - name: login to hub  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: blurred123131/speedjs:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: '160.22.78.169'
          username: 'root'
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            docker pull blurred123131/speedjs:latest
            docker compose up -d

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: '176.126.84.41'
          username: 'root'
          password: ${{ secrets.DEPLOY_PASSWORD2 }}
          script: |
            docker pull blurred123131/speedjs:latest
            cd plex && docker compose up -d
