name: Docker Image build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '/.github/workflows/npm-publish.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '/.github/workflows/npm-publish.yml'

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: login to hub  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: blurred123131/speedjs:latest
