name: Docker Status

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pages/**'
      - 'styles/*'
      - 'postcss.config.js'
      - 'next.config.js'
      - 'package.json'
      - 'postcss.config.js'
      - 'tailwind.config.js'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'pages/**'
      - 'styles/*'
      - 'postcss.config.js'
      - 'next.config.js'
      - 'package.json'
      - 'postcss.config.js'
      - 'tailwind.config.js'
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: login to hub  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: blurred123131/speedjs:latest

      - name: Deploy to Azure
        uses: appleboy/ssh-action@v1
        with:
          host: '68.218.3.24'
          username: 'azureuser'
          key: ${{ secrets.AZURE_KEY }}
          script: |
            sudo docker pull blurred123131/speedjs:latest
            sudo docker compose up -d

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'speedjstestdocker'
          images: 'docker.io/blurred123131:latest'
