name: Sync Cloudflare Repo

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pages/**'
      - 'styles/*'
jobs:
   sync:
    name: Push generated index page to another repository
    runs-on: ubuntu-latest

    steps:
    - name: Push generated index page
      uses: nkoppel/push-files-to-another-repository@v1.1.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'pages/index.js'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: '/functions'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'

      run: rm -rf repo
    - name: Push API
      uses: nkoppel/push-files-to-another-repository@v1.1.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'pages/api/*'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: 'functions/api'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'

      run: rm -rf repo
    - name: Sync Style
      uses: nkoppel/push-files-to-another-repository@v1.1.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'styles/, postcss.config.js'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: '/'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
