name: Sync Cloudflare Repo

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pages/**'
      - 'styles/*'
      - 'next.config.js'
      - 'package.json'
      - 'postcss.config.js'
      - 'tailwind.config.js'
  workflow_dispatch:

jobs:
   sync:
    name: Sync Cloudflare Repo
    runs-on: ubuntu-latest

    steps:
    - name: Push generated index page
      uses: xiliourt/push-files-to-another-repository@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'pages/index.js'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: '/pages'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
        step: 'index'
      
    - name: Sync Style
      uses: xiliourt/push-files-to-another-repository@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'styles/globals.css'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: '/styles'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
        step: 'style'

    - name: Sync Config Files
      uses: xiliourt/push-files-to-another-repository@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: |
              './next.config.js'
              './package.json'
              './postcss.config.js'
              './tailwind.config.js'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: './'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
        step: 'Config'

    - name: Sync API
      uses: xiliourt/push-files-to-another-repository@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'pages/api'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: '/functions/api'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
        step: 'API'
