name: Sync Cloudflare Repo

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pages/**'
      - 'styles/*'
      - 'postcss.config.js'
jobs:
   sync:
    name: Sync Cloudflare Repo
    runs-on: ubuntu-latest

    steps:
    - name: Push generated index page
      uses: xiliourt/push-files-to-another-repository@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'pages/index.js'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: '/pages'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
        step: 'index'
      
    - name: Push API
      uses: xiliourt/push-files-to-another-repository@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'pages/api/*'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: 'functions/api'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
        step: 'api'
      
    - name: Sync Style
      uses: xiliourt/push-files-to-another-repository@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'styles/globals.css'
        destination-username: 'xiliourt'
        destination-repository: 'CFPages-Speedtest-NextJS'
        destination-directory: 'styles/'
        destination-branch: 'main'
        commit-email: 'xiliout@xilout'
        step: 'style'
