name: Push generated index page to another repository

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '/**'
      - '!pages/index.js'
jobs:
   sync:
    name: Push generated index page to another repository
    runs-on: ubuntu-latest

    steps:
    - name: Push generated index page to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'webpage/'
        destination-username: 'nkoppel'
        destination-repository: 'nkoppel.github.io'
        destination-directory: 'projects/my-project'
        commit-email: 'nathankoppel0@gmail.com'
